/**
 * Generates src/constants/icd10.ts from ./icd10-data.ts (the curated subset,
 * kept in sync by hand with eko_telehealth_backend/scripts/icd10-data.ts —
 * see that file's header for why there's no shared package).
 *
 * Run:  npx tsx scripts/build-icd10-subset.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ICD10_SEED_DATA, ICD10_SUBSET_VERSION } from './icd10-data';

const entries = ICD10_SEED_DATA.map(
    (e) =>
      `  { code: ${JSON.stringify(e.code)}, description: ${JSON.stringify(e.description)}, chapter: ${JSON.stringify(e.chapter)}, category: ${JSON.stringify(e.category)}, isBillable: ${e.isBillable}, synonyms: ${JSON.stringify(e.synonyms)} }`,
  )
  .join(',\n');

const output = `/**
 * Generated by scripts/build-icd10-subset.ts from scripts/icd10-data.ts —
 * do not edit by hand. Curated for instant, offline type-ahead in
 * DiagnosisPicker; the long tail is covered by GET /reference/icd10
 * (see src/services/icd10/index.ts).
 */
import type { Icd10Code } from '../api/types';

/** Local-only field the public Icd10Code type doesn't carry over the wire. */
export type Icd10SubsetEntry = Icd10Code & { synonyms: string };

export const ICD10_SUBSET_VERSION = ${JSON.stringify(ICD10_SUBSET_VERSION)};

export const ICD10_SUBSET: Icd10SubsetEntry[] = [
${entries},
];
`;

const outPath = join(__dirname, '..', 'src', 'constants', 'icd10.ts');
writeFileSync(outPath, output);
console.log(`Wrote ${ICD10_SEED_DATA.length} codes to ${outPath}`);
